language: node_js
node_js:
- '4.1'
- '4.0'
- iojs
script: npm run coverage
services:
- redis-server
after_script:
- "./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info"
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage
addons:
  code_climate:
    repo_token: e2f82698af84edf290f4a96bb9ee40d4848fa60d36642e44df3cae7b36e2af92
env:
  global:
    secure: OVS5mbTcMNmzkD/wxPswGY2D61RCwvdit7zaUdFc1RWpKm8vGhxEeNSrhfR8Hb8EfB46TEifZcnXXKdwnivG4yvqG2WQPugysWt8dArnK3Yr84oc0fAEX5YCeW8sa9X5fl7cHsS6SxOPFwb/Iz95TnCp5rOEkckdfL3RVFs5gwj2qhq26nhNRZa1H0kMM4Dyk3kUNCXDwEflvP3xK3iRlPOgNWEIHLoas2saxtBENVF5y6YiaBM344CCh9fW1rqBgwqW8SiNLsRk0b05cDzYbVuCSpWwcAo1QtaVPnp/Rb+kdB0xM5EPSlzOiVYeZCJzStWWT+Wk5JWrzaSF1VROdcMPBTdXtagAGJ9+rHb8SjGpYgdNJBtWWQZLP9uRhkRfRtNXNjOWvSTmXI+lvYbnhw3/ubNbB3BQsUhRlwQMIfee6m9wdyNFK98tlJJy/2TddzOEtO+D5TmFpXSKrQNFAnCsd2SyxJ36ankHaqK25C+X8iuuS9sJgH//UfvhaHx2WvLWWBDEcf2rmH4Tq8q6bOYqwmTAK9JANMR1sjuLt0O1/ZapX7Y1t2UPt1yH0YqK87WOdIgV5QjYFXc2xZNEFQuOwNURO72YVNyQ89DFKtYGgLVabGVljlhps2UbJDkNXXcjdxrXnrrlCGuiq+QsTxUNhWMkbfya597zGgoK36g=
