environment:
  matrix:
  - nodejs_version: '4.1'

install:
  # Install the Redis
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start
  - '@ECHO Redis Started'
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
version: '{build}'

notifications:
  - provider: Slack
    auth_token:
      secure: cjIJaK5AlkGoS3VnrnyIIeP5D39CIlCQj8hNaBryKYCiFIIv+6SxjDs08iQ0Q99YlNQhliGTpBA0ywjCCuVJTg==
    channel: ci
