environment:
  matrix:
  # node.js
  - nodejs_version: '4.1'
  - nodejs_version: '4.0'
  # io.js
  - nodejs_version: '1.0'

install:
  # Install the Redis
  - nuget install redis-64 -excludeversion
  - redis-64\redis-server.exe --service-install
  - redis-64\redis-server.exe --service-start
  - '@ECHO Redis Started'
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
version: '{build}'

